application:
    myKey: "otherValue"
    management:
        endpoints:
            web:
                exposure:
                    include: "*"
    spring:
        sleuth:
            sampler:
                probability: 1.0
        rabbitmq:
            host: "rabbitmq.recon-dc1.local"
            port: 5673
        zipkin:
            baseUrl: "https://zipkin.recon-dc1.local"
example-pubsub:
    myKey: "myValue"
    whoIsADork: "Andy is a dork"
    spring:
        cloud:
            stream:
                bindings:
                    exampleIn:
                        destination: "example"
                    exampleOut:
                        destination: "example"
